/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package geometry;

public class Rectangle {
    private final double length;
    private final double breadth;

    public Rectangle(double length, double breadth) {

        this.length = length;
        this.breadth = breadth;
    }
}
