/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package geometry;

import org.junit.jupiter.api.Test;


import static org.junit.jupiter.api.Assertions.*;

class RectangleTest {
    @Test void testSomeLibraryMethod() {
        Rectangle classUnderTest = new Rectangle();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
