/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package geometry;

import org.junit.jupiter.api.Test;


import static org.junit.jupiter.api.Assertions.*;

class RectangleTest {
    @Test
    void shouldCalculateAreaOfRectangle() {
        final Rectangle rectangle = new Rectangle(2.0, 2.0);
        final double area = rectangle.area();
        assertEquals(4.0, area);
    }
}
